import asyncio
from typing import Dict, Any

async def compare_search_results(query: str) -> str:
    """
    Compares search results between Visual Search (VLM) and Text Search (OCR).
    
    Args:
        query: The user's search query.
        
    Returns:
        A Markdown formatted table comparing the results.
    """
    # Simulate network latency
    await asyncio.sleep(0.5)
    
    # Mock Data
    visual_result = f"Visual match for '{query}'"
    text_result = f"Text match for '{query}'"
    
    # Construct Markdown Table
    markdown_table = f"""
# Search Result Comparison

| Metric | Visual Search (VLM) | Text Search (OCR) |
| :--- | :--- | :--- |
| **Top Match** | {visual_result} | {text_result} |
| **Confidence** | 0.92 | 0.85 |
| **Source File** | product_manual_v2.pdf | product_manual_v2.pdf |
| **Page Number** | 12 | 12 |
| **Key Insight** | Detected object in image | Found text keywords |

*Note: This is a mock comparison generated by the MCP server.*
"""
    return markdown_table
