"""
MCP Tool: Compare Search Results
Visual Agent (MaxSim) vs Text Agent (BM25) comparison for Kibana Agent Builder.
"""
import logging
from typing import Dict, Any, List, Optional

logger = logging.getLogger(__name__)


async def compare_search_results(query: str, num_results: int = 5) -> str:
    """
    Compares search results between Visual Agent (MaxSim) and Text Agent (BM25).

    This tool searches the same query through both agents and returns a
    side-by-side comparison in Markdown format.

    Args:
        query: The user's search query.
        num_results: Number of results to return per agent (default: 5).

    Returns:
        A Markdown formatted comparison of the search results.
    """
    # Import here to avoid circular imports
    from backend.pipelines.ingestion import SearchManager
    from backend.utils.elastic_client import ElasticClient

    try:
        # Check if Elastic is connected
        client = ElasticClient()
        if not client.get_client():
            return _error_response("Elasticsearch not connected. Please check your credentials.")

        # Check if indices have data
        visual_count = client.get_index_count(ElasticClient.VISUAL_INDEX)
        text_count = client.get_index_count(ElasticClient.TEXT_INDEX)

        if visual_count == 0 and text_count == 0:
            return _error_response("No documents indexed. Please ingest some documents first.")

        # Perform search using both agents
        search_manager = SearchManager()
        results = search_manager.search_both(query, size=num_results)

        # Format results as Markdown
        return _format_comparison_markdown(query, results)

    except Exception as e:
        logger.error(f"Search comparison failed: {e}")
        return _error_response(f"Search failed: {str(e)}")


def _format_comparison_markdown(query: str, results: Dict[str, Any]) -> str:
    """Format search results as Markdown comparison table."""

    visual_data = results.get("visual_agent", {})
    text_data = results.get("text_agent", {})

    visual_results = visual_data.get("results", [])
    text_results = text_data.get("results", [])

    visual_latency = visual_data.get("latency_ms", 0)
    text_latency = text_data.get("latency_ms", 0)

    # Header
    md = f"""# 🔍 Search Comparison Results

**Query:** `{query}`

---

## Performance Summary

| Metric | Visual Agent (MaxSim) | Text Agent (BM25) |
|--------|----------------------|-------------------|
| **Results Found** | {len(visual_results)} | {len(text_results)} |
| **Latency** | {visual_latency:.1f}ms | {text_latency:.1f}ms |
| **Search Method** | Late Interaction | Keyword Match |

---

## Top Results Comparison

"""

    # Results table
    max_results = max(len(visual_results), len(text_results))

    if max_results == 0:
        md += "*No results found for either agent.*\n"
    else:
        md += "| Rank | Visual Agent | Text Agent |\n"
        md += "|------|--------------|------------|\n"

        for i in range(max_results):
            visual_cell = _format_result_cell(visual_results[i] if i < len(visual_results) else None)
            text_cell = _format_result_cell(text_results[i] if i < len(text_results) else None)
            md += f"| {i + 1} | {visual_cell} | {text_cell} |\n"

    # Detailed results
    md += "\n---\n\n## Detailed Results\n\n"

    # Visual Agent details
    md += "### 🖼️ Visual Agent (Jina V4 + MaxSim)\n\n"
    if visual_results:
        for i, result in enumerate(visual_results, 1):
            md += f"**{i}. {result.get('file_name', 'Unknown')}** (Page {result.get('page_number', 0) + 1})\n"
            md += f"   - Score: `{result.get('score', 0):.4f}`\n"
            md += f"   - Path: `{result.get('file_path', 'N/A')}`\n\n"
    else:
        md += "*No results from Visual Agent*\n\n"

    # Text Agent details
    md += "### 📝 Text Agent (Docling + BM25)\n\n"
    if text_results:
        for i, result in enumerate(text_results, 1):
            md += f"**{i}. {result.get('file_name', 'Unknown')}** (Page {result.get('page_number', 0) + 1})\n"
            md += f"   - Score: `{result.get('score', 0):.4f}`\n"
            ocr_preview = result.get('ocr_text', '')[:200]
            if ocr_preview:
                md += f"   - Preview: _{ocr_preview}..._\n"
            md += "\n"
    else:
        md += "*No results from Text Agent*\n\n"

    # Footer
    md += """---

*Generated by PolySight Agent Battle - Comparing Late Interaction (Visual) vs BM25 (Text) search.*
"""

    return md


def _format_result_cell(result: Optional[Dict[str, Any]]) -> str:
    """Format a single result for table cell."""
    if not result:
        return "-"

    file_name = result.get("file_name", "Unknown")
    page_num = result.get("page_number", 0) + 1
    score = result.get("score", 0)

    return f"{file_name} (p.{page_num}) `{score:.3f}`"


def _error_response(message: str) -> str:
    """Format error message as Markdown."""
    return f"""# ⚠️ Search Error

{message}

## Troubleshooting

1. **Check Elastic Connection**: Verify `ELASTIC_CLOUD_SERVERLESS_URL` and `ELASTIC_API_KEY` in `.env`
2. **Ingest Documents**: Use the Gradio UI to upload and index documents first
3. **Check Logs**: Review the server logs for detailed error information

---

*PolySight MCP Server*
"""


# Additional tools for MCP

async def get_index_status() -> str:
    """
    Get the current status of PolySight indices.

    Returns:
        Markdown formatted index statistics.
    """
    from backend.utils.elastic_client import ElasticClient

    try:
        client = ElasticClient()

        if not client.get_client():
            return _error_response("Elasticsearch not connected.")

        visual_count = client.get_index_count(ElasticClient.VISUAL_INDEX)
        text_count = client.get_index_count(ElasticClient.TEXT_INDEX)

        return f"""# 📊 PolySight Index Status

| Index | Type | Documents |
|-------|------|-----------|
| `{ElasticClient.VISUAL_INDEX}` | rank_vectors (MaxSim) | {visual_count} |
| `{ElasticClient.TEXT_INDEX}` | text (BM25) | {text_count} |

**Total Documents:** {visual_count + text_count}

---

*Use the Gradio UI at http://localhost:7860 to ingest more documents.*
"""

    except Exception as e:
        return _error_response(f"Failed to get index status: {str(e)}")


async def search_visual_only(query: str, num_results: int = 5) -> str:
    """
    Search using only the Visual Agent (MaxSim).

    Args:
        query: The search query.
        num_results: Number of results to return.

    Returns:
        Markdown formatted search results.
    """
    from backend.pipelines.ingestion import SearchManager

    try:
        manager = SearchManager()
        results, latency = manager.search_visual(query, size=num_results)

        md = f"""# 🖼️ Visual Agent Search Results

**Query:** `{query}`
**Latency:** {latency:.1f}ms
**Results:** {len(results)}

---

"""
        if results:
            for i, result in enumerate(results, 1):
                md += f"### {i}. {result.get('file_name', 'Unknown')}\n"
                md += f"- **Page:** {result.get('page_number', 0) + 1}\n"
                md += f"- **Score:** `{result.get('score', 0):.4f}`\n\n"
        else:
            md += "*No results found.*\n"

        return md

    except Exception as e:
        return _error_response(f"Visual search failed: {str(e)}")


async def search_text_only(query: str, num_results: int = 5) -> str:
    """
    Search using only the Text Agent (BM25).

    Args:
        query: The search query.
        num_results: Number of results to return.

    Returns:
        Markdown formatted search results.
    """
    from backend.pipelines.ingestion import SearchManager

    try:
        manager = SearchManager()
        results, latency = manager.search_text(query, size=num_results)

        md = f"""# 📝 Text Agent Search Results

**Query:** `{query}`
**Latency:** {latency:.1f}ms
**Results:** {len(results)}

---

"""
        if results:
            for i, result in enumerate(results, 1):
                md += f"### {i}. {result.get('file_name', 'Unknown')}\n"
                md += f"- **Page:** {result.get('page_number', 0) + 1}\n"
                md += f"- **Score:** `{result.get('score', 0):.4f}`\n"
                ocr_preview = result.get('ocr_text', '')[:300]
                if ocr_preview:
                    md += f"- **Text Preview:** _{ocr_preview}..._\n"
                md += "\n"
        else:
            md += "*No results found.*\n"

        return md

    except Exception as e:
        return _error_response(f"Text search failed: {str(e)}")
